level = info
level@com.zaxxer.hikari = warn

writerConsole        = console
writerConsole.level  = debug
writerConsole.stream = out

writerConsole.format = \
  {date:yyyy-MM-dd HH:mm:ss.SSS} \
  [{thread}] \
  {level|min-size=5} \
  {class-name}.{method}() - \
  {message}
